// data.js

window.texts = {
    en: {
        "main-title": "🏛️ Oracle AI Agent Studio Foundations Associate",
        subtitle: "Official Certification Simulator - Real Questions",
        welcome: "Welcome to the Official Simulator!",
        description: "Based on real Oracle AI Agent Studio Foundations Associate certification questions. Aim for 93% like the reference candidate!",
        "version-a": "Version A",
        "version-b": "Version B",
        "quiz-info-title": "📋 Simulator Information:",
        "info-1": "20 unique Oracle certification questions per version",
        "info-2": "Questions are randomized for each quiz attempt",
        "info-3": "Focus: Templates, Tools, Security, Metrics",
        "info-4": "Detailed feedback and explanations provided at the end",
        "info-5": "Supports English and Portuguese versions",
        "info-6": "✨ AI-powered enhanced explanations available for each question!",
        "start-quiz": "🚀 Start Simulator",
        "question-label": "Question",
        of: "of",
        previous: "⬅️ Previous",
        next: "Next ➡️",
        finish: "🏁 Finish",
        completed: "🎉 Simulator Completed!",
        "correct-label": "Correct",
        "incorrect-label": "Incorrect",
        "time-used": "Total Time",
        status: "Status",
        restart: "🔄 Try Again",
        "tip-title": "💡 Strategy Tip:",
        approved: "PASSED ✅",
        failed: "FAILED ❌",
        "view-details": "🔍 View Detailed Results",
        "detailed-results-title": "Detailed Results",
        "back-to-summary": "⬅️ Back to Summary",
        your_answer: "Your Answer:",
        correct_answer: "Correct Answer:",
        explanation_label: "Explanation:",
        tip_label: "Strategy Tip:",
        "enhanced-explanation": "✨ Get Enhanced Explanation",
        "fetching-explanation": "Fetching enhanced explanation:",
        "multi-select-instruction": "Please select TWO options.",
        "ai-generated-tag": "(AI-generated Question)",
        "official-tag": "(Official Oracle Certification Question)",
        "key-concepts-label": "Key Concepts to Remember:"
    },
    pt: {
        "main-title": "🏛️ Oracle AI Agent Studio Foundations Associate",
        subtitle: "Simulado Oficial de Certificação - Questões Reais",
        welcome: "Bem-vindo ao Simulado Oficial!",
        description: "Baseado nas questões reais da certificação Oracle AI Agent Studio Foundations Associate. Mire em 93% como o candidato de referência!",
        "version-a": "Versão A",
        "version-b": "Versão B",
        "quiz-info-title": "📋 Informações do Simulado:",
        "info-1": "20 questões únicas da certificação Oracle por versão",
        "info-2": "As questões são randomizadas a cada tentativa do quiz",
        "info-3": "Foco: Templates, Ferramentas, Segurança, Métricas",
        "info-4": "Feedback detalhado e explicações fornecidos no final",
        "info-5": "Suporta versões em Inglês e Português",
        "info-6": "✨ Explicações aprofundadas com IA disponíveis para cada questão!",
        "start-quiz": "🚀 Iniciar Simulado",
        "question-label": "Questão",
        of: "de",
        previous: "⬅️ Anterior",
        next: "Próxima ➡️",
        finish: "🏁 Finalizar",
        completed: "🎉 Simulado Concluído!",
        "correct-label": "Acertos",
        "incorrect-label": "Erros",
        "time-used": "Tempo Total",
        status: "Status",
        restart: "🔄 Tentar Novamente",
        "tip-title": "💡 Dica de Estratégia:",
        approved: "APROVADO ✅",
        failed: "REPROVADO ❌",
        "view-details": "🔍 Ver Resultados Detalhados",
        "detailed-results-title": "Resultados Detalhados",
        your_answer: "Sua Resposta:",
        correct_answer: "Resposta Correta:",
        explanation_label: "Explicação:",
        tip_label: "Dica de Estratégia:",
        "enhanced-explanation": "✨ Obter Explicação Aprofundada",
        "fetching-explanation": "Buscando explicação aprofundada:",
        "multi-select-instruction": "Por favor, selecione DUAS opções.",
        "ai-generated-tag": "(Pergunta gerada por IA)",
        "official-tag": "(Pergunta oficial de certificação Oracle)",
        "key-concepts-label": "Pontos-chave para lembrar:"
    }
};

window.officialQuestionBank = [
    { id: 'q1', type: 'multiple', en: { question: "A supply chain specialist uses the Outbound Compliance Agent template but needs to ensure the agent accounts for recently updated hazardous material regulations. In which two ways can the specialist customize the OCTB agent?", options: [ "Remove access to business object tools to restrict data retrieval", "Create additional topics to address specific regulation updates", "Revise the system prompt to provide information on new regulatory requirements", "Replace the semantic search function with manual document lookup" ], correct: [1, 2], explanation: "To customize OCTB agents, you can create additional topics for specific regulations and revise the system prompt with new regulatory requirements. These are the two main customization methods.", tip: "When the question mentions 'two ways', look for options involving content customization (topics) and configuration (system prompts)." } },
    { id: 'q2', type: 'multiple', en: { question: "A sales leader wants agents to generate customer communications that match their company's tone. Which two customizations should the sales leader make to the agent template?", options: [ "Create additional topics depicting various customer interaction scenarios", "Disable LLM-based content generation", "Limit the agent to internal notification messages only", "Modify the system prompt to specify tone and language preferences" ], correct: [0, 3], explanation: "To ensure agent communications match company tone, the sales leader should create additional topics for interaction scenarios and modify the system prompt to specify tone and language preferences.", tip: "Agent tone and content are primarily controlled by topics and the system prompt." } },
    { id: 'q3', type: 'single', en: { question: "When preparing to test agents in AI Agent Studio, how do you use evaluation test data?", options: [ "Use evaluation test data to automatically fine-tune the LLM behind the agent", "Upload a collection of test inputs and reference answers to compare agent performance during offline testing", "Add evaluation sets to determine which business objects are available to the agent at runtime" ], correct: [1], explanation: "Evaluation test data is used to upload test inputs and reference answers, allowing performance comparison during offline testing before deployment.", tip: "Evaluation testing = Offline comparison. Always involves test inputs and reference answers for validation." } },
    // ... (repita para todas as perguntas em inglês do seu HTML)
]; 